SONARPY-764 Rule S5914: Assertions should not fail or succeed unconditionally
SonarSource/sonar-python pull request #1179
Opened 2022-08-28 21:19 UTC by nils-werner-sonarsource

2022-08-29 14:45 UTC, guillaume-dequenne-sonarsource requested changes
I'm sorry I won't have time to complete the review today, but I already left some comments that I think are worth addressing. We can of course discuss them tomorrow :)

2022-08-29 14:45 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/CheckUtils.java
> +  private static boolean isAlwaysEmptyOrNonEmptyCollection(List<? extends Tree> elements) {
This method name also feels kind of odd - I know you didn't choose it, but it strikes me a bit now that it's in `CheckUtils`.
Probably `doesNotContainUnpackingExpression` is a bit more generic.

2022-08-29 15:21 UTC, nils-werner-sonarsource commented on its/ruling/src/test/resources/expected/python-S5914.json
> +222,
It's a generator expression. Not sure how to handle this in Python.

2022-08-29 15:23 UTC, nils-werner-sonarsource commented on its/ruling/src/test/resources/expected/python-S5914.json
> +194,
Fixed by 59ffcc2f9582face247f0d41d0a06ea91bfb7a63

2022-08-29 15:23 UTC, nils-werner-sonarsource commented on its/ruling/src/test/resources/expected/python-S5914.json
> +482,
Fixed by 59ffcc2f9582face247f0d41d0a06ea91bfb7a63

2022-08-30 07:57 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/resources/expected/python-S5914.json
> +222,
I see, I was surprised at the lack of parentheses (outside of the assert argument, the expression needs to be parenthesized). It's a quite nice TP actually! The expression returns a generator no matter the size or truthiness of the list.

2022-08-30 08:07 UTC, nils-werner-sonarsource commented on its/ruling/src/test/resources/expected/python-S5914.json
> +222,
Whoop Whoop

2022-08-30 08:31 UTC, guillaume-dequenne-sonarsource requested changes
Results are looking good and implementation as well. There are still a few comments from my previous review that were not addressed (I don't really like that we introduce logic specific to a couple of rules in `CheckUtils` class).
Also, there is something weird with keyword arguments for the unittest assertions.
The documentation [here](https://docs.python.org/3.10/library/unittest.html#assert-methods) provides the list of methods and their keyword arguments, which seems to be different from what you use. Weirdly enough, in my local test project, the keywords arguments are also different from both your version and the documentation...If we can't figure why that is, I believe we should default to what is in the documentation.

2022-08-30 08:31 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/tests/UnconditionalAssertionCheck.java
> +        checkIsAssertion(ctx, call, TreeUtils.nthArgumentOrKeyword(1, "secondValue", arguments), message);
Where did you see the keyword is `firstValue` and `secondValue`? In my `unittest.TestCase`, I have `expr1` and `expr2` as keywords (Python 3.10).

2022-08-30 08:31 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/tests/UnconditionalAssertionCheck.java
> +        checkNoneAssertion(ctx, call, TreeUtils.nthArgumentOrKeyword(0, "testValue", arguments));
Here I have `obj` as keyword.

2022-08-30 08:31 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/tests/UnconditionalAssertionCheck.java
> +        checkBooleanAssertion(ctx, TreeUtils.nthArgumentOrKeyword(0, "testValue", arguments));
I have `expr` as keyword locally.

2022-08-30 14:44 UTC, merged