SONARPY-1039 Fix FP on S5806 when the name is an IPython builtin
SonarSource/sonar-python pull request #1198
Opened 2022-09-06 09:39 UTC by nils-werner-sonarsource

2022-09-06 11:42 UTC, andreaguarino requested changes
I think we can use Typeshed builtin Symbols to determine if a name shadows a builtin. Thanks to that the issue would be more precise when the python version is known

2022-09-06 12:08 UTC, nils-werner-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/BuiltinShadowingAssignmentCheck.java
> +    return BUILTINS.contains(name.name());
Changed. It will increase the number of issues and may make the rule noisy.

2022-09-06 12:33 UTC, andreaguarino commented on python-checks/src/main/java/org/sonar/python/checks/BuiltinShadowingAssignmentCheck.java
> +    return BUILTINS.contains(name.name());
are those new issues TPs or FPs?

2022-09-07 13:38 UTC, andreaguarino approved these changes
LGTM. An idea to remove the noise: when the Python version is unknown, we should raise only on Builtins that are available in all python version (this is accessible through `validForPythonVersion()` method.

However, let's maybe check on Peach first

2022-09-07 14:40 UTC, merged