SONARPY-1199
SonarSource/sonar-python pull request #1290
Opened 2022-11-17 10:51 UTC by guillaume-dequenne-sonarsource

2022-11-24 15:39 UTC, gyula-sallai-sonarsource requested changes
Very nice job! I've left a couple of comments, but there is no blocker. I am putting the ticket back into progress, because given the size of the PR, it would be nice to have another quick round of review.

2022-11-24 15:40 UTC, gyula-sallai-sonarsource commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java
> +    boolean shouldOptimizeAnalysis = context.config().getBoolean(SONAR_CAN_SKIP_UNCHANGED_FILES_KEY).orElse(false) && cacheContext.isCacheEnabled();
This comment is outdated, feel free to discard it.

2022-11-25 12:19 UTC, guillaume-dequenne-sonarsource commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java
> +    List<String> impactfulFilesFQN = new ArrayList<>();
As discussed I'll rename the first list to `impactfulFiles` which is more consistent which how it's used and that should already help with the confusion, especially thanks to your other refactoring suggestions.

2022-11-25 12:20 UTC, guillaume-dequenne-sonarsource commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexer.java
> +    }
Very nice suggestion, thanks! That makes the code much cleaner.

2022-11-25 12:22 UTC, guillaume-dequenne-sonarsource commented on sonar-python-plugin/src/test/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexerTest.java
> +    readCache.put(IMPORTS_MAP_CACHE_KEY_PREFIX + "moduleKey:main.py", String.join(";", List.of("mod")).getBytes(StandardCharsets.UTF_8));
I didn't add an additional test, but I added some unresolved imports surrounding the `mod` one being tested. Please let me know if you would like to see something more thorough!

2022-11-25 13:05 UTC, gyula-sallai-sonarsource approved these changes
Looks good to me!

2022-11-25 13:29 UTC, guillaume-dequenne-sonarsource commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonSensor.java
> +    }
Did that on implementation side with a `CacheContextImpl#of` instead, but indeed that cleans things up a bit!

2022-11-25 13:29 UTC, guillaume-dequenne-sonarsource commented on sonar-python-plugin/src/test/java/org/sonar/plugins/python/indexer/SonarQubePythonIndexerTest.java
> +  CacheContextImpl cacheContext;
Yes, and actually doing that made me realize I didn't need some of these (the joy of copy pasting stuff 😅).

2022-11-25 15:01 UTC, merged