SONARPY-1278 Make the quick fix creation part of the public API
SonarSource/sonar-python pull request #1377
Opened 2023-02-09 13:29 UTC by guillaume-dequenne-sonarsource

2023-02-10 08:40 UTC, andreaguarino requested changes

2023-02-10 15:01 UTC, guillaume-dequenne-sonarsource commented on python-frontend/src/main/java/org/sonar/plugins/python/api/PythonCheck.java
> +    public void addQuickFix(PythonQuickFix quickFix){
Indeed, I moved it.

2023-02-20 11:04 UTC, andreaguarino commented on python-frontend/src/main/java/org/sonar/plugins/python/api/PythonCheck.java
> +    public void addQuickFix(PythonQuickFix quickFix){
I would also mark those as "Beta": I think those API make only sense in SonarLint context where custom rules are not supported. So practically we don't expect anyone external to the company to use them.
Can you also add a comment that this API makes only sense for SonarLint and and it's not advisable to use it from a custom rule?

2023-02-20 13:15 UTC, andreaguarino approved these changes

2023-02-20 14:01 UTC, merged