SONARPY-1380: Typeshed third party protobufs serialization should remove older version of protobufs
SonarSource/sonar-python pull request #1483
Opened 2023-06-07 13:11 UTC by joke1196

2023-06-07 15:12 UTC, joke1196 commented on its/ruling/src/test/resources/expected_extended/airflow/python-S930.json
This was an FP linked to older stubs.

2023-06-08 11:50 UTC, joke1196 commented on python-frontend/src/test/java/org/sonar/python/types/TypeShedTest.java
> +    assertThat(baseServer.validForPythonVersions()).isEmpty();
Not 100% sure about this one as we do find the symbol but it is not valid for 27

2023-06-08 15:41 UTC, guillaume-dequenne-sonarsource requested changes
Looks good!
Some minor changes requested.

2023-06-08 15:41 UTC, guillaume-dequenne-sonarsource commented on python-frontend/typeshed_serializer/tests/test_serializers.py
> +
These extra whitespaces are unneeded.

2023-06-08 15:41 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/test/resources/checks/duplicateArgument.py
>  def function_from_typeshed():
I have the feeling this commit could be left out of this PR and merged separately, as it is unrelated to the ticket.

2023-06-09 11:57 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM. Probably you can squash the main changes and the ruling updates.

2023-06-09 13:21 UTC, merged