SONARPY-1521 S4143: Fix FP when there is different collections value assignment for same key
SonarSource/sonar-python pull request #1609
Opened 2023-10-17 10:18 UTC by maksim-grebeniuk-sonarsource

2023-10-20 09:57 UTC, guillaume-dequenne-sonarsource reviewed
I see the fix works but I'm confused why it had to be done that way, it seems we're not really fixing the root cause, given how the rule is supposed to work.

Maybe the rule logic itself is flawed and it's not possible to fix while respecting the rule original idea, but in this case I think it'd deserve some comments at least.

2023-10-20 09:57 UTC, guillaume-dequenne-sonarsource commented on python-checks/src/main/java/org/sonar/python/checks/OverwrittenCollectionEntryCheck.java
> +  private static String key(SubscriptionExpression subscriptionExpression) {
I'm confused that we have to recompute the key part of the subscription here.

As I understand the rule, in `reportOverwrites` we should check for a given key if the writes are made on the same collection. Isn't there where the bug is? It seems that in this method if the 2 collections (not key) are different, we should simply not raise the issue.

2023-10-20 11:44 UTC, guillaume-dequenne-sonarsource requested changes
As we discussed, it would make sense to investigate whether we can fix this bug by fixing the way `reportOverwrites` distinguishes between different collections rather than by changing the way keys are computed.

2023-10-30 08:25 UTC, joke1196 approved these changes
LGTM! Was there a ticket created for the investigation of the problematic `reportOverwrites`?

2023-10-30 09:04 UTC, merged