Rule S6969 : "memory" parameter should be specified for Scikit-Learn Pipeline
SonarSource/sonar-python pull request #1772
Opened 2024-04-25 10:23 UTC by ghislainpiot

2024-04-30 13:23 UTC, joke1196 requested changes
Really good job. The quickfix is super nice! I added just a few suggestions and a small question about possible FPs and test cases not covered.

2024-05-01 07:11 UTC, joke1196 requested changes
LGTM! You just did not address my last question/comment about the closure.

2024-05-01 10:01 UTC, ghislainpiot commented on python-checks/src/test/resources/checks/sklearn_pipeline_specify_memory_argument.py
> +    a_call(b_call(pipeline3))
We only raise an issue on the inner `pipe`, which is the expected behavior

2024-05-01 11:36 UTC, joke1196 approved these changes
LGTM! Thanks for taking of the refactoring

2024-05-01 12:03 UTC, merged