SONARPY-2001:Create GeneratedIPythonFile to hold offset data
SonarSource/sonar-python pull request #1859
Opened 2024-07-22 09:06 UTC by joke1196

2024-07-22 13:00 UTC, ghislainpiot requested changes
I think we only need to store one map in the GeneratedIPythonFile.

I also don't understand how it works, shouldn't there be a way to overwrite the contents of the file ?

2024-07-22 13:18 UTC, joke1196 commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/GeneratedIPythonFile.java
> +  public GeneratedIPythonFile(InputFile wrappedFile, Map<Integer, Offset> offsetMap, Map<Integer, Map<Integer, Integer>> colOffSet) {
You are right we can only rely on the IPython location but we need more than just one column offset per line. And yes sorry I forgot the aggregated content.

2024-07-23 13:53 UTC, ghislainpiot approved these changes
LGTM!

2024-07-23 13:53 UTC, ghislainpiot commented on sonar-python-plugin/src/main/java/org/sonar/plugins/python/GeneratedIPythonFile.java
> +  public GeneratedIPythonFile(InputFile wrappedFile, String pythonContent, Map<Integer, IPythonLocation> offsetMap) {
I think adding the location map and offset map should be done in the ticket that needs it, that way we avoid going back and forth for something that can still change.

2024-07-24 07:49 UTC, merged