SONARPY-1900: Extend S6973 - Important hyperparameters should be specified for Scikit-Learn estimators
SonarSource/sonar-python pull request #1959
Opened 2024-09-10 14:18 UTC by Seppli11

2024-09-12 11:32 UTC, joke1196 commented
Usually we use the name of the ticket as the title of the PR, this is FYI, it is not really important as long as the commit message when squashed is correct.

2024-09-12 11:48 UTC, joke1196 requested changes
This looks quite good. Thank you! I have added a few comments and suggestions. 
I appreciate you split the work into multiple commit, the only thing I could suggest doing here is to do the refactoring (from one class to a private nested class) for SkLearn first in its dedicated commit, 
and in a second time add the PyTorch implementation. This would allow the reviewer to not have a file completely new to review.
This would also help in making sure nothing was broken during the refactoring right away.

2024-09-12 11:48 UTC, joke1196 commented on python-checks/src/test/resources/checks/pytorch_estimator_hyperparameters.py
> +    optimizer = SGD(model.parameters(), **param_dict, *param_list)
I am not sure why but the last two lines of each function are duplicated. Also I would suggest not to test multiple times the same thing.  For example on line 156 your are testing that we do not raise on spread operator, but this is already tested on line 145.

2024-09-16 10:09 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/SklearnPyTorchEstimatorHyperparametersCheck.java
> +    private static boolean containsSpreadOperator(CallExpression callExpression) {
Would it make sens to do this in a separate PR?

2024-09-16 15:05 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/SklearnPyTorchEstimatorHyperparametersCheck.java
> +    private static boolean containsSpreadOperator(CallExpression callExpression) {
@joke1196 mentioned that this should be done in a new PR. The issue is https://sonarsource.atlassian.net/browse/SONARPY-2140

2024-09-19 13:08 UTC, joke1196 approved these changes
LGTM!

2024-09-19 13:10 UTC, merged