SONARPY-1711: Rule S5659: do not raise under certain use of get_unverified_header()
SonarSource/sonar-python pull request #2041
Opened 2024-10-04 12:04 UTC by joke1196

2024-10-04 14:25 UTC, Seppli11 requested changes
Is it on purpose that something like `foo(jwt.get_unverified_header(token).get("x5u"))` or `return jwt.get_unverified_header(token).get("x5u")` is not compliant? 
If yes, I think, a test case should be added to document this.  

Apart from this I've made a comment when `TreeUtils.toStreamInstanceOfMapper` can be used instead of first filtering and then mapping.

Otherwise, it looks good

EDIT: fixed the second example

2024-10-04 14:25 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/JwtVerificationCheck.java
> +  private static Stream<Usage> getHeaderDictUsages(Symbol symbol, CallExpression call) {
I think a name, which indicates that only usages after the definition are returned, might be better. E.g. `getForwardUsages`

2024-10-04 14:25 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/JwtVerificationCheck.java
> +      .map(TreeUtils.toInstanceOfMapper(QualifiedExpression.class))
Can be replaced with the following:
```suggestion
      .flatMap(TreeUtils.toStreamInstanceOfMapper(QualifiedExpression.class))
```

2024-10-04 14:25 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/JwtVerificationCheck.java
> +      .map(TreeUtils.toInstanceOfMapper(CallExpression.class));
Could be written as
```suggestion
      .map(QualifiedExpression::parent)
      .flatMap(TreeUtils.toStreamInstanceOfMapper(CallExpression.class));
```

2024-10-04 14:25 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/JwtVerificationCheck.java
> +      .map(TreeUtils.toInstanceOfMapper(RegularArgument.class))
```suggestion
    return arguments
      .flatMap(TreeUtils.toStreamInstanceOfMapper(RegularArgument.class))
```

2024-10-04 14:25 UTC, Seppli11 commented on python-checks/src/main/java/org/sonar/python/checks/JwtVerificationCheck.java
> +      .filter(Objects::nonNull);
```suggestion
      .flatMap(TreeUtils.toStreamInstanceOfMapper(StringLiteral.class));
```

2024-10-07 07:22 UTC, joke1196 commented
So the first is not specified in the ticket but I would think it should be compliant, I will fix this. The second is documented in the ticket and in test cases as the token passed to the function does not affect how we would raise issues.

2024-10-07 08:58 UTC, Seppli11 approved these changes
lgtm!

2024-10-07 08:58 UTC, merged

2026-03-30 10:50 UTC, mrwensveen commented
This has been merged for a while now, but I think there's a mistake on line 80 of JwtVerificationCheck.java:
`"jose.jws.get_unverified_claims"` should be `"jose.jws.get_unverified_claim"` because `"jose.jws.get_unverified_claims"` is added on the line above.