SONARPY-2068: Tabulations (\t) should be handled correctly as an escape character
SonarSource/sonar-python pull request #2050
Opened 2024-10-08 12:01 UTC by Seppli11

2024-10-08 14:55 UTC, Seppli11 commented on sonar-python-plugin/src/test/java/org/sonar/plugins/python/TestUtils.java
> +  public static List<ColumnMapping> mapToColumnMappingList(Map<Integer, Integer> map) {
Do you have a `TestUtils` that is accessible in all tests?

2024-10-10 11:27 UTC, joke1196 requested changes
Looks really good. Thanks for the clean up! I have added a small suggestion for the naming as well as small change on test. As stated in my comment we should add code for something that we do not support (unicode escape sequences), but I think this is fine like so as it is a way better version than what was there already :) (which already had code for something we were not using)

2024-10-10 11:27 UTC, joke1196 commented on sonar-python-plugin/src/test/java/org/sonar/plugins/python/PythonHighlighterTest.java
> +    String pythonContent = """
Maybe in the highlighter we could add a `\t` to one of the test. To be sure the impact of the changes you made are propagated here.

2024-10-10 12:47 UTC, joke1196 approved these changes
LGTM! Thanks a lot for this. This clean up was really needed!

2024-10-10 15:42 UTC, merged